# Generated by Django 5.1.3 on 2024-12-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(default='', max_length=100)),
                ('book_authors', models.CharField(default='', max_length=150)),
                ('book_description', models.CharField(default='', max_length=500)),
                ('book_selfLink', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
