# Generated by Django 5.1.3 on 2025-01-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_alter_book_book_authors_alter_book_book_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_selfLink',
            field=models.CharField(default='', help_text='Link do livro', max_length=255),
        ),
    ]
